/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_operatoroverloaded_hotel_stores_hotelcustomerstore_InMemoryHotelCustomerStore */

#ifndef _Included_com_operatoroverloaded_hotel_stores_hotelcustomerstore_InMemoryHotelCustomerStore
#define _Included_com_operatoroverloaded_hotel_stores_hotelcustomerstore_InMemoryHotelCustomerStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_operatoroverloaded_hotel_stores_hotelcustomerstore_InMemoryHotelCustomerStore
 * Method:    loadFromFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_operatoroverloaded_hotel_stores_hotelcustomerstore_InMemoryHotelCustomerStore_loadFromFile
  (JNIEnv *, jobject);

/*
 * Class:     com_operatoroverloaded_hotel_stores_hotelcustomerstore_InMemoryHotelCustomerStore
 * Method:    storeToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_operatoroverloaded_hotel_stores_hotelcustomerstore_InMemoryHotelCustomerStore_storeToFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
