/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore */

#ifndef _Included_com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore
#define _Included_com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore
#ifdef __cplusplus
extern "C" {
#endif
#undef com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore_serialVersionUID
#define com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore_serialVersionUID 1LL
/*
 * Class:     com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore
 * Method:    deleteRoom
 * Signature: (I)Lcom/operatoroverloaded/hotel/models/Room;
 */
JNIEXPORT jobject JNICALL Java_com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore_deleteRoom
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore
 * Method:    updateRoom
 * Signature: (ILcom/operatoroverloaded/hotel/models/Room;)V
 */
JNIEXPORT void JNICALL Java_com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore_updateRoom
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore
 * Method:    findRoom
 * Signature: (I)Lcom/operatoroverloaded/hotel/models/Room;
 */
JNIEXPORT jobject JNICALL Java_com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore_findRoom
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore
 * Method:    saveToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore_saveToFile
  (JNIEnv *, jobject);

/*
 * Class:     com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore
 * Method:    loadFromFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_operatoroverloaded_hotel_stores_roomstore_InMemoryRoomStore_loadFromFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
