/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_operatoroverloaded_hotel_stores_billstore_InMemoryBillStore */

#ifndef _Included_com_operatoroverloaded_hotel_stores_billstore_InMemoryBillStore
#define _Included_com_operatoroverloaded_hotel_stores_billstore_InMemoryBillStore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_operatoroverloaded_hotel_stores_billstore_InMemoryBillStore
 * Method:    loadBill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_operatoroverloaded_hotel_stores_billstore_InMemoryBillStore_loadBill
  (JNIEnv *, jobject);

/*
 * Class:     com_operatoroverloaded_hotel_stores_billstore_InMemoryBillStore
 * Method:    saveBill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_operatoroverloaded_hotel_stores_billstore_InMemoryBillStore_saveBill
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
