/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_operatoroverloaded_hotel_stores_staffstore_InMemoryStaffStore */

#ifndef _Included_com_operatoroverloaded_hotel_stores_staffstore_InMemoryStaffStore
#define _Included_com_operatoroverloaded_hotel_stores_staffstore_InMemoryStaffStore
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_operatoroverloaded_hotel_stores_staffstore_InMemoryStaffStore
 * Method:    loadStaff
 * Signature: ()V
 * Description: Loads staff data from the "staff.txt" file into the Java `ArrayList`.
 */
JNIEXPORT void JNICALL Java_com_operatoroverloaded_hotel_stores_staffstore_InMemoryStaffStore_loadStaff
  (JNIEnv *, jobject);

/*
 * Class:     com_operatoroverloaded_hotel_stores_staffstore_InMemoryStaffStore
 * Method:    saveStaff
 * Signature: ()V
 * Description: Saves staff data from the Java `ArrayList` to the "staff.txt" file.
 */
JNIEXPORT void JNICALL Java_com_operatoroverloaded_hotel_stores_staffstore_InMemoryStaffStore_saveStaff
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
